version: "3.7"
services:
  knxd:
    container_name: knxd
    build:
      context: .
      dockerfile: Dockerfile
#      args:                                                                      
#        KNXD_VERSION: 0.14.39
    ports:
      - "6720:6720/tcp"
      - "3671:3671/udp"
    cap_add:
      - SYS_RAWIO
      - SYS_MODULE
    restart: unless-stopped
    devices:
      - /dev/knx
      - /dev/bus/usb:/dev/bus/usb:rwm
      - /dev/mem:/dev/mem:rw
